p8105_hw2_msj2167
================
2026-10-07

Loading libraries

``` r
library(tidyverse)
library(readxl)
```

## Problem 2

#### Importing and merging the datasets

To combine the three trash wheel datasets, I imported and cleaned each
sheet separately so that the variables would have the same names and
formats. For each sheet, I used the range argument to read only the data
cells that were necessary. I cleaned the variable names and removed any
rows without a dumpster number using drop_na(dumpster). I also added a
trash_wheel variable to each dataset to identify which trash wheel
collected the trash, which would also help me identify which rows came
from which original data sheet. Some variables were stored differently
across sheets, so I converted them to matching types: year was stored as
text in the Mr. Trash Wheel sheet, so I converted it to numeric, and
plastic_bottles was stored as a character variable in the Professor
Trash Wheel sheet, so I converted it to numeric to match the other
datasets. I also rounded the number of sports balls to the nearest
integer and converted it to an integer variable for the Mr. Trash Wheel
data.

``` r
mr_trash_wheel_df =
  read_excel("Data/202610 Trash Wheel Collection Data.xlsx", 
  sheet = "Mr. Trash Wheel",
  range = "A2:N742",
  na=c(".", "", "NA")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
    mutate(
      sports_balls= as.integer(round(sports_balls)),
      trash_wheel = "Mr. Trash Wheel",
      year = as.numeric(year),
    )
```

Import Professor Trash Wheel

``` r
prof_trash_wheel_df =
  read_excel("Data/202610 Trash Wheel Collection Data.xlsx", 
  sheet = "Professor Trash Wheel",
  range = "A2:M139",
  na=c(".", "", "NA")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
    mutate(
   trash_wheel = "Professor Trash Wheel",
 plastic_bottles = as.numeric(plastic_bottles)
 )
```

Import Gwynnda

``` r
gwynnda_df =
  read_excel("Data/202610 Trash Wheel Collection Data.xlsx", 
  sheet = "Gwynnda the Good Wheel of the W",
  range = "A2:L394",
  na=c(".", "", "NA")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
   mutate(
   trash_wheel = "Gwynnda")
```

Merging the datasets

``` r
trash_df = 
  bind_rows(mr_trash_wheel_df, prof_trash_wheel_df, gwynnda_df)
```

#### Dataset description

In the trash_df dataset there are 1269 observations and 15 variables.
Some of the key variables are dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered,
trash_wheel.

The total weight collected by Professor Trash Wheel was 294.96 tons.

The total number of cigarette butts collected by Gwynnda in June of 2022
was 18,120

## Problem 3

#### Importing MCI_baseline dataset

When importing the data I created two dataframes, one to clean the data
and that contained all participants who were recruited and another that
filtered participants based on the inclusion criteria of being MCI-free
at baseline. I skipped the first row, which contained a code book and
also specified in the code that blank cells, “NA”, and “.” should be
treated as missing values. I cleaned the variable names and recoded sex
and APOE4 status to have meaningful descriptive labels instead of
numeric codes. When removing any participants who do not meet the stated
inclusion criteria, I had to make sure to look into those who had NA for
age_at_onset as it was missing if a subject remains MCI free during the
follow-up period. I also kept participants whose age at onset was
greater than their baseline age, since they developed MCI after
enrolling.

``` r
mci_recruitment_df =
  read_csv(
    file = "data/MCI_baseline.csv",
    skip = 1,
    na = c("", "NA", ".")) |>
  janitor::clean_names() |>
  mutate(
  sex = recode_values(
    sex,
    1 ~ "male",
    0 ~ "female"),
  apoe4 = recode_values(
    apoe4,
    1 ~ "carrier",
    0 ~ "non-carrier"))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline_df =
  filter(mci_recruitment_df, is.na(age_at_onset) | age_at_onset > current_age)
```

There were 483 participants recruited. After excluding those with MCI at
baseline, 479 participants remained, of whom 93 developed MCI during
follow-up.

The average baseline age was 65

The proportion of women who were APOE4 carriers 30%

#### Importing and cleaning the longitudinally observed biomarker dataset

To clean this data, I first looked at the raw file and noticed that the
first line was a codebook, so I made sure to skip it when importing. The
codebook indicates that the values are amyloid β 42/40 ratios measured
at baseline and at 2, 4, 6, and 8 years after baseline. I noticed when
looking at the raw data file that missing values were not coded
consistently. Some were recorded as “NA” and others as “Na,” which
caused the biomarker columns to be read as character variables. I
specified both as missing values during import so the columns were read
as numeric. The data was originally in wide format, with one column per
visit, so I used pivot_longer() to convert them to a tidy long format
with one row per participant per visit and each variable as its own
column. I then recoded “baseline” as 0 and converted time to a numeric
variable representing years since baseline.

``` r
mci_amyloid_df =
  read_csv(
    file = "data/mci_amyloid.csv",
    skip = 1,
    na = c("", "NA", ".", "Na")) |>
  janitor::clean_names() |>
  pivot_longer(
    baseline:time_8, 
    names_to = "years_since_baseline",
    names_prefix = "time_",
    values_to = "amyloid_ratio"
    ) |>
    mutate(
      years_since_baseline = replace(years_since_baseline, years_since_baseline == "baseline", "0"),
    years_since_baseline = as.numeric(years_since_baseline)
    )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The final dataset contains 487 participants and 2435 rows, with
variables for study_id, years_since_baseline, amyloid_ratio.
